# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2022.10.11-haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2021.4.0-haa95532_3556.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2022g-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-2021.4.0-haa95532_640.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://repo.anaconda.com/pkgs/main/win-64/bzip2-1.0.8-he774522_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libffi-3.4.2-hd77b12b_6.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1s-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.40.0-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.12-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/xz-5.2.8-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.13-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.10.8-h966fe2a_1.conda
https://repo.anaconda.com/pkgs/main/win-64/certifi-2022.12.7-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py310haa95532_2.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py310h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-65.5.0-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.23.5-py310h04254f7_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-22.3.1-py310haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.1-py310ha0764ea_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.2-py310h4ed8f06_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.23.5-py310h60c9a35_0.conda
